services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: optum_db
    ports:
      - "5432:5432"    
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
    # command waits for db to be ready, before running any scripts to avoid errors. 
    command: >
      bash -c "
        python src/main.py;
      "